# Generated by Django 4.1.1 on 2022-09-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="location",
            field=models.CharField(default="", max_length=200),
        ),
    ]
