# Generated by Django 4.1.1 on 2022-09-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_car_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="cars"),
        ),
    ]
